# Generated by Django 5.0.6 on 2024-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_aso_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
