# Generated by Django 5.0.6 on 2024-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_address_item_email_item_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
