# Generated by Django 5.0.6 on 2024-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_birthday_item_phone_item_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
