# Generated by Django 5.0.6 on 2024-07-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_item_phone_alter_item_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
