# Generated by Django 5.0.6 on 2024-07-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_item_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
