# Generated by Django 5.0.6 on 2024-07-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_item_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
