# Generated by Django 5.0.6 on 2024-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_item_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
