# Generated by Django 5.0.6 on 2024-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bloodType',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='civilStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gsisIdNo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='heightM',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weightKg',
            field=models.IntegerField(null=True),
        ),
    ]
