# Generated by Django 5.0.6 on 2024-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_item_sss_no_item_tin_no_item_agencyemployeeno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fatherFirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fatherMiddleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fatherSurName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='motherFirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='motherMiddleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='motherSurname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
