# Generated by Django 5.0.7 on 2024-07-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_item_fatherfirstname_item_fathermiddlename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vocational',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
